[2024-09-02T07:08:34.112+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-02T07:08:34.134+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag_v5.second_task manual__2024-09-02T07:08:32.420646+00:00 [queued]>
[2024-09-02T07:08:34.145+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag_v5.second_task manual__2024-09-02T07:08:32.420646+00:00 [queued]>
[2024-09-02T07:08:34.145+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 6
[2024-09-02T07:08:34.162+0000] {taskinstance.py:2879} INFO - Executing <Task(BashOperator): second_task> on 2024-09-02 07:08:32.420646+00:00
[2024-09-02T07:08:34.172+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2238) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-02T07:08:34.174+0000] {standard_task_runner.py:72} INFO - Started process 2239 to run task
[2024-09-02T07:08:34.173+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag_v5', 'second_task', 'manual__2024-09-02T07:08:32.420646+00:00', '--job-id', '388', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmpuscn0s7n']
[2024-09-02T07:08:34.175+0000] {standard_task_runner.py:105} INFO - Job 388: Subtask second_task
[2024-09-02T07:08:34.245+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag_v5.second_task manual__2024-09-02T07:08:32.420646+00:00 [running]> on host efc48c282cbe
[2024-09-02T07:08:34.360+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ubeyd' AIRFLOW_CTX_DAG_ID='my_first_dag_v5' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2024-09-02T07:08:32.420646+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-02T07:08:32.420646+00:00'
[2024-09-02T07:08:34.361+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-02T07:08:34.379+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-02T07:08:34.380+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hey, I am task2 and will be running after task1']
[2024-09-02T07:08:34.392+0000] {subprocess.py:86} INFO - Output:
[2024-09-02T07:08:34.395+0000] {subprocess.py:93} INFO - hey, I am task2 and will be running after task1
[2024-09-02T07:08:34.396+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-02T07:08:34.425+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-02T07:08:34.426+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=my_first_dag_v5, task_id=second_task, run_id=manual__2024-09-02T07:08:32.420646+00:00, execution_date=20240902T070832, start_date=20240902T070834, end_date=20240902T070834
[2024-09-02T07:08:34.470+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-09-02T07:08:34.480+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
