[2024-09-02T07:25:38.024+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-02T07:25:38.042+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_cathcup_backfill_v1.task1 manual__2024-09-02T07:25:37.695662+00:00 [queued]>
[2024-09-02T07:25:38.049+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_cathcup_backfill_v1.task1 manual__2024-09-02T07:25:37.695662+00:00 [queued]>
[2024-09-02T07:25:38.049+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 6
[2024-09-02T07:25:38.063+0000] {taskinstance.py:2879} INFO - Executing <Task(BashOperator): task1> on 2024-09-02 07:25:37.695662+00:00
[2024-09-02T07:25:38.072+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=3103) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-02T07:25:38.073+0000] {standard_task_runner.py:72} INFO - Started process 3105 to run task
[2024-09-02T07:25:38.072+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_cathcup_backfill_v1', 'task1', 'manual__2024-09-02T07:25:37.695662+00:00', '--job-id', '428', '--raw', '--subdir', 'DAGS_FOLDER/cathcup_and_backfill_dag.py', '--cfg-path', '/tmp/tmphcyzm2sj']
[2024-09-02T07:25:38.074+0000] {standard_task_runner.py:105} INFO - Job 428: Subtask task1
[2024-09-02T07:25:38.117+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_cathcup_backfill_v1.task1 manual__2024-09-02T07:25:37.695662+00:00 [running]> on host efc48c282cbe
[2024-09-02T07:25:38.192+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ubeyd' AIRFLOW_CTX_DAG_ID='dag_with_cathcup_backfill_v1' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2024-09-02T07:25:37.695662+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-02T07:25:37.695662+00:00'
[2024-09-02T07:25:38.193+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-02T07:25:38.206+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-02T07:25:38.207+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo This is a simple bash command!']
[2024-09-02T07:25:38.217+0000] {subprocess.py:86} INFO - Output:
[2024-09-02T07:25:38.219+0000] {subprocess.py:93} INFO - This is a simple bash command!
[2024-09-02T07:25:38.219+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-02T07:25:38.243+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-02T07:25:38.243+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_with_cathcup_backfill_v1, task_id=task1, run_id=manual__2024-09-02T07:25:37.695662+00:00, execution_date=20240902T072537, start_date=20240902T072538, end_date=20240902T072538
[2024-09-02T07:25:38.288+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-09-02T07:25:38.304+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-02T07:25:38.307+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
