[2024-09-02T07:08:34.114+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-02T07:08:34.136+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag_v5.second_task scheduled__2024-08-31T00:00:00+00:00 [queued]>
[2024-09-02T07:08:34.147+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag_v5.second_task scheduled__2024-08-31T00:00:00+00:00 [queued]>
[2024-09-02T07:08:34.147+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 6
[2024-09-02T07:08:34.167+0000] {taskinstance.py:2879} INFO - Executing <Task(BashOperator): second_task> on 2024-08-31 00:00:00+00:00
[2024-09-02T07:08:34.181+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2233) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-02T07:08:34.179+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag_v5', 'second_task', 'scheduled__2024-08-31T00:00:00+00:00', '--job-id', '394', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmpc59gtsko']
[2024-09-02T07:08:34.182+0000] {standard_task_runner.py:72} INFO - Started process 2241 to run task
[2024-09-02T07:08:34.183+0000] {standard_task_runner.py:105} INFO - Job 394: Subtask second_task
[2024-09-02T07:08:34.256+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag_v5.second_task scheduled__2024-08-31T00:00:00+00:00 [running]> on host efc48c282cbe
[2024-09-02T07:08:34.362+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ubeyd' AIRFLOW_CTX_DAG_ID='my_first_dag_v5' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2024-08-31T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-31T00:00:00+00:00'
[2024-09-02T07:08:34.364+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-02T07:08:34.380+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-02T07:08:34.381+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hey, I am task2 and will be running after task1']
[2024-09-02T07:08:34.393+0000] {subprocess.py:86} INFO - Output:
[2024-09-02T07:08:34.395+0000] {subprocess.py:93} INFO - hey, I am task2 and will be running after task1
[2024-09-02T07:08:34.396+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-02T07:08:34.425+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-02T07:08:34.426+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=my_first_dag_v5, task_id=second_task, run_id=scheduled__2024-08-31T00:00:00+00:00, execution_date=20240831T000000, start_date=20240902T070834, end_date=20240902T070834
[2024-09-02T07:08:34.483+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-09-02T07:08:34.492+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
