[2024-09-02T07:37:56.609+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-02T07:37:56.626+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_cathcup_backfill_v2.task1 manual__2024-09-02T07:37:56.057066+00:00 [queued]>
[2024-09-02T07:37:56.634+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_cathcup_backfill_v2.task1 manual__2024-09-02T07:37:56.057066+00:00 [queued]>
[2024-09-02T07:37:56.635+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 6
[2024-09-02T07:37:56.650+0000] {taskinstance.py:2879} INFO - Executing <Task(BashOperator): task1> on 2024-09-02 07:37:56.057066+00:00
[2024-09-02T07:37:56.657+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=3793) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-02T07:37:56.658+0000] {standard_task_runner.py:72} INFO - Started process 3794 to run task
[2024-09-02T07:37:56.657+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_cathcup_backfill_v2', 'task1', 'manual__2024-09-02T07:37:56.057066+00:00', '--job-id', '440', '--raw', '--subdir', 'DAGS_FOLDER/cathcup_and_backfill_dag.py', '--cfg-path', '/tmp/tmpqqqiwevp']
[2024-09-02T07:37:56.659+0000] {standard_task_runner.py:105} INFO - Job 440: Subtask task1
[2024-09-02T07:37:56.704+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_cathcup_backfill_v2.task1 manual__2024-09-02T07:37:56.057066+00:00 [running]> on host efc48c282cbe
[2024-09-02T07:37:56.799+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ubeyd' AIRFLOW_CTX_DAG_ID='dag_with_cathcup_backfill_v2' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2024-09-02T07:37:56.057066+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-02T07:37:56.057066+00:00'
[2024-09-02T07:37:56.800+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-02T07:37:56.814+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-02T07:37:56.815+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo This is a simple bash command!']
[2024-09-02T07:37:56.825+0000] {subprocess.py:86} INFO - Output:
[2024-09-02T07:37:56.827+0000] {subprocess.py:93} INFO - This is a simple bash command!
[2024-09-02T07:37:56.827+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-02T07:37:56.860+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-02T07:37:56.861+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_with_cathcup_backfill_v2, task_id=task1, run_id=manual__2024-09-02T07:37:56.057066+00:00, execution_date=20240902T073756, start_date=20240902T073756, end_date=20240902T073756
[2024-09-02T07:37:56.913+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-09-02T07:37:56.930+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-02T07:37:56.936+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
