[2024-08-30T09:41:16.432+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-30T09:41:16.449+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_taskflow_api_v01.get_name manual__2024-08-30T09:39:42.648345+00:00 [queued]>
[2024-08-30T09:41:16.457+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_taskflow_api_v01.get_name manual__2024-08-30T09:39:42.648345+00:00 [queued]>
[2024-08-30T09:41:16.457+0000] {taskinstance.py:2856} INFO - Starting attempt 2 of 7
[2024-08-30T09:41:16.470+0000] {taskinstance.py:2879} INFO - Executing <Task(_PythonDecoratedOperator): get_name> on 2024-08-30 09:39:42.648345+00:00
[2024-08-30T09:41:16.477+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=6653) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-30T09:41:16.478+0000] {standard_task_runner.py:72} INFO - Started process 6655 to run task
[2024-08-30T09:41:16.478+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_taskflow_api_v01', 'get_name', 'manual__2024-08-30T09:39:42.648345+00:00', '--job-id', '328', '--raw', '--subdir', 'DAGS_FOLDER/taskflow_api_dag.py', '--cfg-path', '/tmp/tmpe0o8ahtu']
[2024-08-30T09:41:16.480+0000] {standard_task_runner.py:105} INFO - Job 328: Subtask get_name
[2024-08-30T09:41:16.522+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_taskflow_api_v01.get_name manual__2024-08-30T09:39:42.648345+00:00 [running]> on host efc48c282cbe
[2024-08-30T09:41:16.607+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ubeyd' AIRFLOW_CTX_DAG_ID='dag_with_taskflow_api_v01' AIRFLOW_CTX_TASK_ID='get_name' AIRFLOW_CTX_EXECUTION_DATE='2024-08-30T09:39:42.648345+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-30T09:39:42.648345+00:00'
[2024-08-30T09:41:16.608+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-30T09:41:16.610+0000] {python.py:240} INFO - Done. Returned value was: Jerry
[2024-08-30T09:41:16.631+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-30T09:41:16.631+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_with_taskflow_api_v01, task_id=get_name, run_id=manual__2024-08-30T09:39:42.648345+00:00, execution_date=20240830T093942, start_date=20240830T094116, end_date=20240830T094116
[2024-08-30T09:41:16.653+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-08-30T09:41:16.675+0000] {taskinstance.py:3891} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-30T09:41:16.678+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
