[2024-09-03T09:37:35.863+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-03T09:37:35.880+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_python_dependencies_v2.get_matplotlib scheduled__2024-09-01T00:00:00+00:00 [queued]>
[2024-09-03T09:37:35.888+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_python_dependencies_v2.get_matplotlib scheduled__2024-09-01T00:00:00+00:00 [queued]>
[2024-09-03T09:37:35.889+0000] {taskinstance.py:2856} INFO - Starting attempt 2 of 2
[2024-09-03T09:37:35.903+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): get_matplotlib> on 2024-09-01 00:00:00+00:00
[2024-09-03T09:37:35.914+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=279) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-03T09:37:35.914+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_python_dependencies_v2', 'get_matplotlib', 'scheduled__2024-09-01T00:00:00+00:00', '--job-id', '479', '--raw', '--subdir', 'DAGS_FOLDER/python_dependencies_dag.py', '--cfg-path', '/tmp/tmpkc7fbs5r']
[2024-09-03T09:37:35.915+0000] {standard_task_runner.py:72} INFO - Started process 280 to run task
[2024-09-03T09:37:35.915+0000] {standard_task_runner.py:105} INFO - Job 479: Subtask get_matplotlib
[2024-09-03T09:37:35.962+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_python_dependencies_v2.get_matplotlib scheduled__2024-09-01T00:00:00+00:00 [running]> on host 01a3c7586b71
[2024-09-03T09:37:36.048+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ubeyd' AIRFLOW_CTX_DAG_ID='dag_with_python_dependencies_v2' AIRFLOW_CTX_TASK_ID='get_matplotlib' AIRFLOW_CTX_EXECUTION_DATE='2024-09-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-01T00:00:00+00:00'
[2024-09-03T09:37:36.049+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-03T09:37:36.374+0000] {logging_mixin.py:190} INFO - matplotlib with version: 3.9.2
[2024-09-03T09:37:36.375+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-03T09:37:36.384+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-03T09:37:36.385+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_with_python_dependencies_v2, task_id=get_matplotlib, run_id=scheduled__2024-09-01T00:00:00+00:00, execution_date=20240901T000000, start_date=20240903T093735, end_date=20240903T093736
[2024-09-03T09:37:36.410+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-09-03T09:37:36.427+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-03T09:37:36.430+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
