[2024-08-30T08:58:55.330+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-30T08:58:55.350+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag_with_python_operator_v05.get_name manual__2024-08-30T08:58:54.470071+00:00 [queued]>
[2024-08-30T08:58:55.360+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag_with_python_operator_v05.get_name manual__2024-08-30T08:58:54.470071+00:00 [queued]>
[2024-08-30T08:58:55.361+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 6
[2024-08-30T08:58:55.377+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): get_name> on 2024-08-30 08:58:54.470071+00:00
[2024-08-30T08:58:55.385+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=4241) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-30T08:58:55.387+0000] {standard_task_runner.py:72} INFO - Started process 4242 to run task
[2024-08-30T08:58:55.386+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_dag_with_python_operator_v05', 'get_name', 'manual__2024-08-30T08:58:54.470071+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/python_operator_dag.py', '--cfg-path', '/tmp/tmp_samuxnz']
[2024-08-30T08:58:55.387+0000] {standard_task_runner.py:105} INFO - Job 16: Subtask get_name
[2024-08-30T08:58:55.431+0000] {task_command.py:467} INFO - Running <TaskInstance: my_dag_with_python_operator_v05.get_name manual__2024-08-30T08:58:54.470071+00:00 [running]> on host efc48c282cbe
[2024-08-30T08:58:55.504+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ubeyd' AIRFLOW_CTX_DAG_ID='my_dag_with_python_operator_v05' AIRFLOW_CTX_TASK_ID='get_name' AIRFLOW_CTX_EXECUTION_DATE='2024-08-30T08:58:54.470071+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-30T08:58:54.470071+00:00'
[2024-08-30T08:58:55.506+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-30T08:58:55.545+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-08-30T08:58:55.555+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-30T08:58:55.556+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=my_dag_with_python_operator_v05, task_id=get_name, run_id=manual__2024-08-30T08:58:54.470071+00:00, execution_date=20240830T085854, start_date=20240830T085855, end_date=20240830T085855
[2024-08-30T08:58:55.602+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-08-30T08:58:55.623+0000] {taskinstance.py:3891} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-30T08:58:55.626+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
