[2024-09-13T03:55:39.686+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-13T03:55:39.782+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v3.delete_data_from_table scheduled__2024-09-07T00:00:00+00:00 [queued]>
[2024-09-13T03:55:39.827+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v3.delete_data_from_table scheduled__2024-09-07T00:00:00+00:00 [queued]>
[2024-09-13T03:55:39.830+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 6
[2024-09-13T03:55:39.886+0000] {taskinstance.py:2879} INFO - Executing <Task(PostgresOperator): delete_data_from_table> on 2024-09-07 00:00:00+00:00
[2024-09-13T03:55:39.916+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=347) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-13T03:55:39.924+0000] {standard_task_runner.py:72} INFO - Started process 381 to run task
[2024-09-13T03:55:40.014+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v3', 'delete_data_from_table', 'scheduled__2024-09-07T00:00:00+00:00', '--job-id', '536', '--raw', '--subdir', 'DAGS_FOLDER/postgres_operator_dag.py', '--cfg-path', '/tmp/tmpocljhppp']
[2024-09-13T03:55:40.018+0000] {standard_task_runner.py:105} INFO - Job 536: Subtask delete_data_from_table
[2024-09-13T03:55:40.238+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_postgres_operator_v3.delete_data_from_table scheduled__2024-09-07T00:00:00+00:00 [running]> on host 01a3c7586b71
[2024-09-13T03:55:40.653+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ubeyd' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v3' AIRFLOW_CTX_TASK_ID='delete_data_from_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-07T00:00:00+00:00'
[2024-09-13T03:55:40.658+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-13T03:55:40.692+0000] {sql.py:282} INFO - Executing: 
            delete from dag_runs where dt = '2024-09-07' and dag_id = 'dag_with_postgres_operator_v3'
        
[2024-09-13T03:55:41.409+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-13T03:55:41.789+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-13T03:55:41.890+0000] {sql.py:509} INFO - Running statement: 
            delete from dag_runs where dt = '2024-09-07' and dag_id = 'dag_with_postgres_operator_v3'
        , parameters: None
[2024-09-13T03:55:41.918+0000] {sql.py:518} INFO - Rows affected: 0
[2024-09-13T03:55:42.004+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-13T03:55:42.005+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v3, task_id=delete_data_from_table, run_id=scheduled__2024-09-07T00:00:00+00:00, execution_date=20240907T000000, start_date=20240913T035539, end_date=20240913T035542
[2024-09-13T03:55:42.110+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-09-13T03:55:42.270+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
