[2024-09-13T03:55:36.170+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-13T03:55:36.200+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_python_dependencies_v2.get_sklearn scheduled__2024-09-06T00:00:00+00:00 [queued]>
[2024-09-13T03:55:36.216+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_python_dependencies_v2.get_sklearn scheduled__2024-09-06T00:00:00+00:00 [queued]>
[2024-09-13T03:55:36.217+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2024-09-13T03:55:36.382+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): get_sklearn> on 2024-09-06 00:00:00+00:00
[2024-09-13T03:55:36.404+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=214) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-13T03:55:36.405+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_python_dependencies_v2', 'get_sklearn', 'scheduled__2024-09-06T00:00:00+00:00', '--job-id', '522', '--raw', '--subdir', 'DAGS_FOLDER/python_dependencies_dag.py', '--cfg-path', '/tmp/tmpv0q3vbqg']
[2024-09-13T03:55:36.408+0000] {standard_task_runner.py:72} INFO - Started process 229 to run task
[2024-09-13T03:55:36.408+0000] {standard_task_runner.py:105} INFO - Job 522: Subtask get_sklearn
[2024-09-13T03:55:36.533+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_python_dependencies_v2.get_sklearn scheduled__2024-09-06T00:00:00+00:00 [running]> on host 01a3c7586b71
[2024-09-13T03:55:36.719+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ubeyd' AIRFLOW_CTX_DAG_ID='dag_with_python_dependencies_v2' AIRFLOW_CTX_TASK_ID='get_sklearn' AIRFLOW_CTX_EXECUTION_DATE='2024-09-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-06T00:00:00+00:00'
[2024-09-13T03:55:36.721+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-13T03:55:40.277+0000] {logging_mixin.py:190} INFO - scikit-learn with version: 1.5.1
[2024-09-13T03:55:40.293+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-13T03:55:40.611+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-13T03:55:40.638+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_with_python_dependencies_v2, task_id=get_sklearn, run_id=scheduled__2024-09-06T00:00:00+00:00, execution_date=20240906T000000, start_date=20240913T035536, end_date=20240913T035540
[2024-09-13T03:55:41.777+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2024-09-13T03:55:41.756+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-09-13T03:55:42.031+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-13T03:55:42.056+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
