[2024-09-13T03:55:42.805+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-13T03:55:42.864+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_python_dependencies_v2.get_matplotlib scheduled__2024-09-05T00:00:00+00:00 [queued]>
[2024-09-13T03:55:42.899+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_python_dependencies_v2.get_matplotlib scheduled__2024-09-05T00:00:00+00:00 [queued]>
[2024-09-13T03:55:42.901+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2024-09-13T03:55:42.947+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): get_matplotlib> on 2024-09-05 00:00:00+00:00
[2024-09-13T03:55:42.990+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=405) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-13T03:55:42.996+0000] {standard_task_runner.py:72} INFO - Started process 436 to run task
[2024-09-13T03:55:42.994+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_python_dependencies_v2', 'get_matplotlib', 'scheduled__2024-09-05T00:00:00+00:00', '--job-id', '547', '--raw', '--subdir', 'DAGS_FOLDER/python_dependencies_dag.py', '--cfg-path', '/tmp/tmpqabsslfo']
[2024-09-13T03:55:42.998+0000] {standard_task_runner.py:105} INFO - Job 547: Subtask get_matplotlib
[2024-09-13T03:55:43.249+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_python_dependencies_v2.get_matplotlib scheduled__2024-09-05T00:00:00+00:00 [running]> on host 01a3c7586b71
[2024-09-13T03:55:43.589+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ubeyd' AIRFLOW_CTX_DAG_ID='dag_with_python_dependencies_v2' AIRFLOW_CTX_TASK_ID='get_matplotlib' AIRFLOW_CTX_EXECUTION_DATE='2024-09-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-05T00:00:00+00:00'
[2024-09-13T03:55:43.599+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-13T03:55:47.704+0000] {logging_mixin.py:190} INFO - matplotlib with version: 3.9.2
[2024-09-13T03:55:47.711+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-13T03:55:47.746+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-13T03:55:47.747+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_with_python_dependencies_v2, task_id=get_matplotlib, run_id=scheduled__2024-09-05T00:00:00+00:00, execution_date=20240905T000000, start_date=20240913T035542, end_date=20240913T035547
[2024-09-13T03:55:47.877+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-09-13T03:55:48.024+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2024-09-13T03:55:48.040+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
